# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyter/scipy-base:v1 

LABEL maintainer="Jupyter Caffe2"

USER root

# If need the gcc env, please comment out below line
#RUN apt-get update && apt-get -yq dist-upgrade \
# && apt-get install -yq --no-install-recommends \
#    build-essential 

# Install caffe and caffe2 packages
# Caffe 
#RUN conda install --quiet --yes  caffe && \


# Caffe2  
# please vist the URL https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=prebuilt to check more verions for cpu or gpu
#RUN conda install --quiet --yes  -c caffe2 caffe2 && \
RUN conda install --yes \
    'qt=5.9.*' \
    'pyqt=5.9.*'  && \
    conda install --yes  -c caffe2 caffe2 && \
    conda remove --quiet --yes --force qt pyqt && \
    conda clean -tipsy && \
    npm cache clean --force && \
    rm -rf $CONDA_DIR/share/jupyter/lab/staging && \
    rm -rf /home/.cache/yarn && \
    rm -rf /home/.node-gyp 
