# base on tensorflow
FROM tensorflow/tensorflow
MAINTAINER limingkun 144650984@qq.com
LABEL Description="This image is the base os tensorflow."  Version="1.0"
RUN apt-get update && apt-get install -yq --no-install-recommends\
    vim
USER root
